id = "0x0"
name = "0x0"
description = "The open source coding agent."
version = "1.1.53"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/anomalyco/0x0"

[agent_servers.0x0]
name = "0x0"
icon = "./icons/0x0.svg"

[agent_servers.0x0.targets.darwin-aarch64]
archive = "https://github.com/anomalyco/0x0/releases/download/v1.1.53/0x0-darwin-arm64.zip"
cmd = "./0x0"
args = ["acp"]

[agent_servers.0x0.targets.darwin-x86_64]
archive = "https://github.com/anomalyco/0x0/releases/download/v1.1.53/0x0-darwin-x64.zip"
cmd = "./0x0"
args = ["acp"]

[agent_servers.0x0.targets.linux-aarch64]
archive = "https://github.com/anomalyco/0x0/releases/download/v1.1.53/0x0-linux-arm64.tar.gz"
cmd = "./0x0"
args = ["acp"]

[agent_servers.0x0.targets.linux-x86_64]
archive = "https://github.com/anomalyco/0x0/releases/download/v1.1.53/0x0-linux-x64.tar.gz"
cmd = "./0x0"
args = ["acp"]

[agent_servers.0x0.targets.windows-x86_64]
archive = "https://github.com/anomalyco/0x0/releases/download/v1.1.53/0x0-windows-x64.zip"
cmd = "./0x0.exe"
args = ["acp"]
