name: 0x0

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  0x0:
    if: |
      contains(github.event.comment.body, ' /oc') ||
      startsWith(github.event.comment.body, '/oc') ||
      contains(github.event.comment.body, ' /0x0') ||
      startsWith(github.event.comment.body, '/0x0')
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      id-token: write
      contents: read
      pull-requests: read
      issues: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-bun

      - name: Run 0x0
        uses: anomalyco/0x0/github@latest
        env:
          ZEROXZERO_API_KEY: ${{ secrets.ZEROXZERO_API_KEY }}
          ZEROXZERO_PERMISSION: '{"bash": "deny"}'
        with:
          model: 0x0/claude-opus-4-5
